language: ruby
rvm: 2.6.4
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  # - RAILS_ENV=test bundle exec rspec

# whitelist
branches:
  only:
    - develop
    - master
