# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa6dbea267f67728eb60091ff62869a336740932ae5cb19e147cec8d772d0ae1dcbac94d750ba64297ad310fd8f4d1b4dee082597c1944df67ecffddcf932d3c

test:
  secret_key_base: 0764caa147567059870c453cc969ea944db1bf51842a3162b8881e9818fb1367966b3b349751c984460da1529f5ba58c8bb43db4dd923a78050d908f9bb18fe8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
